import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

  
 
import { useFetchUsersQuery } from "../fetures/users/users-api-clice";
import { useFetchBreedsQuery } from "../fetures/dogs/dogs-api-slice";
 
import React from "react";
 
 
 
export   function Users() {

  const { data = [], isFetching } = useFetchUsersQuery(10);

  return (
    <>
    <h1>A list of Users</h1>
      <p> {data.users && data.users.length} users fetched</p>
        <div>
          {data.users && data.users.map((breed) => (
            <li key={breed.id}>{breed.name}</li>
          ))}
        </div> 

    </>
  );
}

 

// export async function getStaticProps() {
//   const res = await fetch("http://localhost:3000/api/users");
//   const data =await res.json();
//   // console.log(data);
  
//   return {
//     props: {
//       users:data.users
//     },
//   }
// };
export default function Home(
  { } 
) {
   
  const { data = [], isFetching } = useFetchBreedsQuery(2);
 
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main className={styles.main}>
          <h1 className={styles.title}>Dogs /Users API</h1>

        <p> {data && data.length} Dogs fetched</p>
        <div>
          {data && data.map((breed) => (
            <li key={breed.id}>{breed.name}</li>
          ))}
        </div>  
 <Users/>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
